### ISSUE TITLE
When scanning QR codes, there’s a partial black frame around the camera.

### ISSUE THREAD

**Issue by sdsdsasad12312** [tijme/raivo#2]
https://i.imgur.com/bRjLiXP.jpg

 - Device: iPhone 7 Plus 
 - OS: iOS 13 developer beta 5
 - Version: 0.0.10 build 10

**Comment by tijme** [comment]
That looks a bit weird! I haven't seen this issue on the iPhone 7 Plus before, therefore I might think this is due to iOS 13. I hope to fix this in the next release! Thank you for the bug report.

**Comment by tijme** [comment]
Hi @sdsdsasad12312,

Would you mind beta testing the fix for this issue via TestFlight? I haven't got an iPhone Plus which I can test on. On the simulator it works but that tells me nothing, since it worked on the simulator before this fix.

You can use this invite link for TestFlight: [this invite link](https://testflight.apple.com/join/wLhhxcjP)

The build containing this fix will be "Release v1.0.1 (build-12)"

**Comment by tijme** [comment]
Closing this issue as inactive. Feel free to reopen it if needed.
