### ISSUE TITLE
FaceID option not present, only TouchID.

### ISSUE THREAD

**Issue by mil1i** [tijme/raivo#3]
**Describe the bug**
Description says 'Optional FaceID or TouchID unlock. However, on iPhone XS the only option I have is to enable TouchID. Selecting this option asks for the iPhone PIN with iPhone XS. Deselecting does not provide an option for FaceID.

**To Reproduce**
1. Go to 'Settings'
2. FaceID option is missing

**Expected behavior**
The option for FaceID or TouchID should be relevant to the device which the application is running on. Devices that do not posses TouchID should not have the option, and vice-versa with FaceID.

https://developer.apple.com/documentation/localauthentication/logging_a_user_into_your_app_with_face_id_or_touch_id

**Screenshots**
![raivo](https://user-images.githubusercontent.com/8459426/62406492-e59d5e00-b569-11e9-9343-777e7a1d77cc.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 12.4
 - Version: Raivo 0.0.10

**Comment by tijme** [comment]
Thank you for the detailed bug report/explanation. This is something that I hope to fix in the next release, since I advertised that this should work.

**Comment by tijme** [comment]
Hi @mil1i,

I just pushed dda49c1012c6f305b47c83aec0993902055edb99 & 89af73b8745adab6b9d77083b965fedf8701129c to the `develop` branch.

These commits change the text "TouchID unlock" to "Biometric unlock". However, this change shouldn't have prevented FaceID from working.

I think the problem was that I missed the "NSFaceIDUsageDescription" key in the `Info.plist` file. However, I'm unable to verify if this fixed the issue. I don't have an iPhone with FaceID so I am only able to use the simulator. On the simulator it works, but it also worked before I added that key in the `Info.plist` file.

Would you mind joining the beta program to test if these patches fix the FaceID bug? You can join the beta by using [this invite link](https://testflight.apple.com/join/wLhhxcjP). Version 1.0.0 (which contains the FaceID bug) will soon be available in TestFlight.

**Comment by mil1i** [comment]
@tijme,

I joined the program. Currently it shows version 0.0.10 in TestFlight. I will check for version 1.0.0 and let you know.

**Comment by tijme** [comment]
@mil1i I haven't uploaded it to TestFlight yet. When I have, it will take a few days to be approved and then I'll publish it in TestFlight. I'll give you a ping when it's ready. It will be somewhere next week.

**Comment by tijme** [comment]
Release v1.0.0 contains the FaceID description. I just pushed it to the invite link you used and it should be available within a few days (once Apple finishes the review). Lets hope this fixes the issue! 🤞 

![Screenshot 2019-08-06 at 21 34 43](https://user-images.githubusercontent.com/5873573/62571600-0f1ff780-b892-11e9-89b5-030e8c812d07.png)

**Comment by mil1i** [comment]
Just downloaded the 1.0.0 update. FaceID is working now! 🥳👍

**Comment by tijme** [comment]
Thanks for reporting and testing!
